### ISSUE TITLE
Highlighting fails on hyphenated tags

### ISSUE THREAD

**Issue by command-tab** [tommasongr/nova-vue#31]
Thank you for building this Nova extension! ❤️ I ran into this little bug today...

In places where DOM templates use kebab-case, nova-vue fails to highlight hyphenated tags:

![image](https://user-images.githubusercontent.com/3069/116842848-db6f2000-ab92-11eb-8621-527a61545ddc.png)

Notice that `nuxt-link` highlighting stops highlighting the Vue tag (styled green by my theme) at `nuxt-` but doesn't include `link`. Could the match pattern for tags be updated to include hyphens? Or is that out of scope of this extension, and something that's better suited to the Nova HTML highlighter?

Thanks!

**Comment by tommasongr** [comment]
Hi there! Thanks for enjoying Nova Vue 😄

I'm sorry for the issue... Yesterday I pushed an update but I haven't touched the syntax highlighting. Have you ever encountered this problem with the prior versions?

Anyway I'll look at it as soon as possible. Can you tell me what theme are you using? Maybe it's a problem of how the Vue special highlighting is implemented in the theme.

Thanks

**Comment by command-tab** [comment]
Thanks for the fast reply!

I did encounter the issue before the 4.1 release. Yesterday I updated to 4.1 hoping it would fix it, but it made no change.

I'm using my own custom editor theme with my preferred colors, but this particular highlighting issue persists no matter what Nova editor theme I switch to; I see the same issue just in different colors. Here it is in the Dark theme that ships with Nova:

![image](https://user-images.githubusercontent.com/3069/116903674-91695700-abf1-11eb-955c-2f7d31baaff3.png)

I suppose this is a good reason for me to switch to using PascalCase for Vue component names 🤔

**Comment by tommasongr** [comment]
No unfortunately 4.1 was focused on Language Server and JS related stuff.

Thanks for the explanation, I'll look at the default Dark theme and let you know.

No don't worry, we'll fix it. Kebab-case feels way better to me ahahah

**Comment by tommasongr** [comment]
Hi again! That has been an easy one! I just pushed v4.2 that solves the issue.

Just to be sure, did you experienced this issue with other tags too? I ask because the extension treats some tags like nuxt-link as special ones. In fact, the problem was that I missed to specify the kabab-case version of NuxtLink.

Here is the list of all the special tags. If you think I missed something let me know 😄

<img width="807" alt="CleanShot 2021-05-03 at 19 24 21@2x" src="https://user-images.githubusercontent.com/25225746/116910099-6577c100-ac45-11eb-81f6-4436d7704bb2.png">

**Comment by command-tab** [comment]
Ah, you're right, it looks like `nuxt-link` is the only one. Other hyphenated tags are highlighted as plain HTML tags. 🙌🏻  4.2 fixes `nuxt-link`. Thank you!!

**Comment by tommasongr** [comment]
You are welcome!
